# Generated by Django 2.0.3 on 2019-04-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
